department-of-veterans-affairs/va-forms-system-core

package.json
=> Scope the name to @department-of-veterans-affairs

package-lock.json, package.json
Because we're using both of them in development and require the downstream project to use them.
=> Add Formik and web-components as dev and peer dependencies

package.json, src/form-builder/TextField.tsx, src/form-builder/types.ts, test/form-builder/TextField.test.tsx, test/utils.tsx
Adds tests for the `TextField` component.
=> TextField tests

src/form-builder/CheckboxField.tsx, src/form-builder/TextField.tsx, src/form-builder/index.ts, test/form-builder/CheckboxField.test.tsx, test/utils.tsx
Closes https://github.com/department-of-veterans-affairs/formulate/issues/9
Adds the CheckboxField and associated tests.
=> CheckboxField

jest.config.js, package-lock.json, package.json, src/form-builder/SelectField.tsx, src/form-builder/index.ts, src/utils/validation.ts, test/form-builder/SelectField.test.tsx, test/utils.tsx
Closes https://github.com/department-of-veterans-affairs/formulate/issues/10
=> Add SelectField wrapper

examples/simple-form/index.jsx, src/form-builder/RadioGroup.tsx
No ticket, fixes radio component to ensure it renders options
=> Fix radio component render

examples/burial-form/BurialAllowance.jsx, examples/burial-form/MilitaryServiceHistory.jsx, examples/burial-form/VeteranInformation.jsx, examples/burial-form/index.jsx
Adds plot allowance page
department-of-veterans-affairs/va-forms-system-core#343
1. <img width="569" alt="Screen Shot 2022-06-01 at 9 58 57 AM" src="https://user-images.githubusercontent.com/2727868/171459907-0cf73c49-78ca-4704-bd56-8f47c9619564.png">
2. <img width="580" alt="Screen Shot 2022-06-01 at 9 59 13 AM" src="https://user-images.githubusercontent.com/2727868/171459941-d1b06f5e-3d42-4637-b861-453bf1b9817b.png">
3. <img width="616" alt="Screen Shot 2022-06-01 at 9 59 18 AM" src="https://user-images.githubusercontent.com/2727868/171460038-d25d5ef0-be9a-49eb-9b89-da6be297e46b.png">
- [+] Documentation has been updated, if applicable
- [+] A link to the original github issue has been provided
- [+] No sensitive information (i.e. PII/credentials/internal URLs etc.) is captured in …
=> Adds burial allowance page.

.eslintrc.js, examples/burial-form/BurialInformation.jsx, examples/burial-form/ClaimantInformation.jsx, examples/burial-form/MilitaryServiceHistory.jsx, examples/burial-form/VeteranInformation.jsx, examples/burial-form/index.jsx, examples/burial-form/utils.ts, package.json, yarn.lock
This PR adds the burial information page to the burials form prototype. It also centralizes before date validation and adds some typescript rules. 
department-of-veterans-affairs/va-forms-system-core#301
- local
=> 301 burial information page

src/form-builder/AddressField.tsx
We have been getting build warning for a circular dependency so I removed it.
=> fix: remove circle dependency from address field

examples/burial-form/ClaimantContactInformation.jsx, examples/burial-form/index.jsx
department-of-veterans-affairs/va-forms-system-core#0000
=> Create Claimant Contact Information page

package.json, yarn.lock
Updated the component-library to the newest version to fix the `Date` web-component, required validation error.
=> fix: updating comp-lib to fix date required

examples/burial-form/ReviewPage.jsx, src/routing/Page.tsx, src/routing/Router.tsx, src/routing/RouterContext.tsx, test/routing/Router.test.tsx
- Review page navigation - editing then going back to the review page should scroll the section into view
- Hide sections that are conditional (burial allowance and plot allowance)
department-of-veterans-affairs/va-forms-system-core#393
=> Feature/393 Additional routing issues

examples/Constant.js, examples/burial-form/BurialAllowance.jsx, examples/burial-form/BurialInformation.jsx, examples/burial-form/ReviewPage.jsx, src/form-builder/DateField.tsx, src/utils/constants.ts, src/utils/validation.ts
Co-authored-by: Anish <obliviga@users.noreply.github.com>
Co-authored-by: Harshil Moradia <harshil1793@gmail.com>
Quick bug fixes in the mob session to correct some small mistakes in our Burial demo form
=> burial form fixes

examples/burial-form/PlotAllowance.jsx, examples/burial-form/PreviousNames.jsx, examples/burial-form/utils.ts, src/form-builder/RadioGroup.tsx
department-of-veterans-affairs/va-forms-system-core#420
=> Adds changes to radio group button.

package.json
Upgrading the package.json version to 0.0.3 so that we can pull all latest components and routing for other tickets.
[department-of-veterans-affairs/va-forms-system-core#465](https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/va-forms-system-core/465)
=> feat: bumping package.json version to 0.0.3

examples/burial-form/index.jsx, package.json, src/routing/Chapter.tsx, src/routing/ConditionalRoute.tsx, src/routing/FormRouter.tsx, src/routing/Page.tsx, src/routing/RouterContext.tsx, test/form-layout/FormFooter.test.tsx, test/form-layout/FormTitle.test.tsx, test/routing/Chapter.test.tsx, test/routing/Page.test.tsx, test/routing/Router.test.tsx, test/routing/RouterContext.test.tsx, test/routing/RouterProgress.test.tsx, yarn.lock
department-of-veterans-affairs/va-forms-system-core#0000
=> Mc react router compat

examples/burial-form/MilitaryServiceHistory.jsx, examples/burial-form/PreviousNames.jsx, src/routing/Page.tsx
Quick bug fixes from [Adding VaButton and VaButtonPair in VAFSC](https://github.com/department-of-veterans-affairs/va-forms-system-core/pull/508)
[department-of-veterans-affairs/va-forms-system-core#511](https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/va-forms-system-core/511)
=> fix: bug cleanup fixes around VaButtons

.github/workflows/npm-publish.yml
Changing back for now have to work out issues with permissions to commit to main since we have branch protection rules applied.
=> fix: revert semantic versioning

src/routing/Page.tsx, test/routing/Chapter.test.tsx, test/routing/Page.test.tsx, test/routing/RouterProgress.test.tsx
Changes from https://github.com/department-of-veterans-affairs/va-forms-system-core/pull/508 caused markup changes which broke some tests, and those failing tests were skipped. This updates the 4 skipped tests so that they can run again. This also has some changes which fix the way the button components are rendered on `<Page>`.
I also found test for `Chapter` that was [skipped before `<VaButton>` was used](https://github.com/department-of-veterans-affairs/va-forms-system-core/blob/df78dbf0a7c2a057f7ef5683d080dc6587ae1a4e/test/routing/Chapter.test.tsx#L72) and updated that to pass as well.
N/A
Unit tests
=> Fix buttons on Page & update skipped tests

.github/workflows/npm-publish.yml
Reverts department-of-veterans-affairs/va-forms-system-core#519
=> Revert "fix: adding permissions for bot to push to main"

doc-extraction/va-forms-system-core.api.md, docs/reference/va-forms-system-core.addressfield.md, docs/reference/va-forms-system-core.md, src/form-builder/AddressField.tsx
Testing the fix(<number>) commit message.
=> fix(123): adding placeholder tsdoc to test fix()

examples/index.jsx, examples/simple-form/index.jsx, package.json
Fixed the validation error on the SimpleApp example page by adding the parent name to each option so formik knows what to validate against.
[department-of-veterans-affairs/va-forms-system-core#494](https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/va-forms-system-core/494)
=> fix(494): fixed checkboxGroup validation and reorganized simple form

src/form-data/ReviewPage.tsx
Comment PR so I can make our release and npm version in sync.
=> feat(444): Dynamic Review Page

examples/simple-form/index.jsx
Adding non memorable date to simple form and pushing to bump github release to match NPM version
[department-of-veterans-affairs/va-forms-system-core#546](https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/va-forms-system-core/546)
=> fix(562): adding non memorable date

examples/burial-form/MilitaryServiceHistory.jsx, package.json
As a user with cognitive issues, it is helpful when simplified choices are made available for form fields that have pre-defined options available.
https://github.com/department-of-veterans-affairs/va-forms-system-core/issues/556
=> Replace military service history TextField with SelectField

examples/burial-form/BurialInformation.jsx, examples/burial-form/ClaimantInformation.jsx
See details in the original issue: https://github.com/department-of-veterans-affairs/va-forms-system-core/issues/564
=> [#564] Update form labels to be more specific

examples/simple-form/index.jsx
Fix Github release for 1.4.4 fix around review page styles.
[department-of-veterans-affairs/va-forms-system-core#561](https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/va-forms-system-core/561)
=> fix(1.4.4): review page styles and cleanup

package.json, src/form-data/ReviewPage.tsx
Adding the `id` back to the `h2` on the `ReviewPage` component so that the `On this page` section will show the links to each section of the page.
department-of-veterans-affairs/va-forms-system-core#0000
=> fix(on-this-page): fixed the on this page bug on review page
