department-of-veterans-affairs/va-forms-system-core

- docs/_config.yml
It turns out that I needed to do a bit of extra work to get the site to work in Pages, even though it worked locally.
Followup for #31 
In addition to the change here, I tried making changes directly to master :grimacing: :
- https://github.com/department-of-veterans-affairs/formulate/commit/5a745588cda9f11ddd381f95595aeeb9959b34e2
- https://github.com/department-of-veterans-affairs/formulate/commit/f001d413b06f890bd595b90f84db2a07b709de9d
After making the change on this branch, and changing the settings in the repo to build Pages based on `pages-testing`, I confirmed that things work:
> Get the site to work with GH Pages

- examples/simple-form/index.jsx
- src/form-builder/CheckboxField.tsx
- src/form-builder/SelectField.tsx
- src/form-builder/TextField.tsx
- test/form-builder/CheckboxField.test.tsx
- test/form-builder/TextField.test.tsx
Closes #7 
Use the React bindings for `TextField` and `CheckboxField`.
> Use react bindings for TextField & CheckboxField

- examples/webpack.config.js
Use webpack module resolution to get `yarn link`ed packages to not use two versions of `React` (which will, of course, break things).
> Get locally-linked packages to work

- .github/CODEOWNERS
- .github/workflows/formulate-testing.yml
- .github/workflows/npm-publish.yml
Adding formulate testing action:
- Building the application using the setup-node action
1. Runs ```yarn install``` to install all needed packages
2. Runs ```yarn build``` to build and place all files in the appropriate place
3. Runs ```yarn test``` to run all tests that will be used for branch requirement
Adding NPM publish action:
- Builds the application and pushes it to the NPM repo @department-of-veterans-affairs/formulate
1. Runs ```yarn install```, ```yarn build```, then ```npm publish``` using NPM Auth Token
P.S. - The NPM Publish command will use the name specified in the package.json file to push to the correct package when we create a "Release" on this repo
> Adding formulate testing and npm publish actions

- .github/workflows/formulate-testing.yml
This repository has "master" and not "main" so need to update this in the Formulate-testing action to make it available
> master branch fix for formulate-testing

- .github/workflows/npm-publish.yml
We want the tolerate-republish flag to:
"Warn and exit when republishing an already existing version of a package"
adding yarn in from of the npm publish command
> using yarn npm publish to allow tolerate-republish

- .github/CODEOWNERS
Updating the name of the DST Github team in codeowners
department-of-veterans-affairs/va-forms-system-core#0000
> updating design system team name in codeowners

- examples/simple-form/index.jsx
- src/form-builder/FullNameField.tsx
- src/form-builder/types.ts
- test/form-builder/FullNameField.test.tsx
1. Passing dynamic id
2. Instead of a custom prop `name` need to be used to describe the object as shown below.
department-of-veterans-affairs/va-forms-system-core#219
Yes, changed the reader component to reflect the change in the functionality.
> fix: required name prop for FullNameField

- examples/burial-form/ClaimantInformation.jsx
- examples/burial-form/VeteranInformation.jsx
Fixing issues around props not being defined in claimant-information and adding the usage of props in the veteran-information page.
> fix: updating using props for example pages

- examples/burial-form/BurialAllowance.jsx
- examples/burial-form/index.jsx
This PR adds the Burial Allowance page. The behavior of the page is as follows:
- The first radio button has 2 options by default, or 3 options if the location of death property is set to a VA Medical Center or a Nursing Home
- If the second option (`Non-service-connected death`) is selected, a warning label should show below the radio button group
- If the third option (`VA medical center death`) is selected, a currency input for Actual Burial Cost should show below the radio button group
- A second radio button will only show if the Relationship.Type property (on the very first page of the form) is set to "spouse" or "other" 
- If the property is set to "spouse", a T/F radio group with the label, "Did you previously receive a VA burial allowance?" will show
- If the property is set to …
> 305 - Burial Allowance Page

- examples/server.js
- examples/webpack.config.js
- package.json
- yarn.lock
This PR upgrades the webpack config to allow for `client side routing`. This will enable the users of our `burials example form` to be able to navigate between pages using the address bar and not only relying on the navigation links inside of the form.
[department-of-veterans-affairs/va-forms-system-core#370](https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/va-forms-system-core/370)
- Page Loads here: 
- Now type in the route `http://localhost:3000/veteran-information`:
> fix: url routing is now working for serve-examples

- examples/burial-form/ConfirmationPage.jsx
- examples/burial-form/ReviewPage.jsx
- examples/burial-form/index.jsx
- src/routing/RouterProgress.tsx
- test/routing/RouterContext.test.tsx
- test/routing/RouterProgress.test.tsx
This PR ensures that the index page and confirmation pages in a form will not show the progress bar component, while the review page and other pages will.
department-of-veterans-affairs/va-forms-system-core#0366
> 366 Progress Bar Navigation - Intro and Confirmation page

- src/form-builder/SSNField.tsx
This PR fixes the ssn mask on initial load if value exists.
- Once SSN value is entered and then navigating between pages or coming back from review page SSN will be masked and showed in the SSN Field.
department-of-veterans-affairs/va-forms-system-core#384
Yes
> fix: ssn mask on initial load

- examples/burial-form/BurialInformation.jsx
This PR fixes the 'Please specify' field for 'Where did the Veteran's death occur?' when other is deslected.
department-of-veterans-affairs/va-forms-system-core#391
Yes
> fix: clearing field condition for burial info

- src/form-builder/CheckboxFieldGroup.tsx
- test/form-builder/CheckboxFieldGroup.test.tsx
This PR makes it so that CheckboxFieldGroups and their underlying checkboxes can point to flat data, rather than only nested data. Previously, the field a checkbox had to point to was `{CheckboxFieldGroups.name}.{CheckboxField.name}`. Now, we are just pointing to `CheckboxField.name`
department-of-veterans-affairs/va-forms-system-core#0376
> 376 flatten checkbox fields

- examples/burial-form/BenefitsSelection.jsx
- examples/burial-form/schema.js
- examples/form-styles.css
- src/form-builder/CheckboxField.tsx
- src/form-builder/CheckboxFieldGroup.tsx
- src/form-builder/RadioGroup.tsx
- src/routing/Page.tsx
- src/routing/Router.tsx
- src/routing/RouterContext.tsx
- src/utils/validation.ts
- test/form-builder/CheckboxFieldGroup.test.tsx
- Adds onBlur functionality to some custom fields
- Removes unneeded second validation from some validator functions
- Moves form to higher level router level
- resets form `errors` and `touched` at page level `useEffect`
department-of-veterans-affairs/va-forms-system-core#363
✅
> 363 Page Level Validation

- src/routing/Page.tsx
- src/routing/types.ts
This change will allow engineers to configure the CTA to begin a form to have an `aria-describedby` attribute, so that screen reader users can know if there is additional information that the button is described by. This prop is optional.
https://github.com/department-of-veterans-affairs/va-forms-system-core/issues/330
Yes
Example of the prop being used:
> [#330] Add an ariaDescribedby prop to the CTA of the form

- .github/workflows/npm-publish.yml
Changing to NPM_TOKEN instead to try and get passed pipeline error.
> fix: changing to NPM_TOKEN for semantic-release

- .github/workflows/npm-publish.yml
Reverting this change for now until I get my branch configured properly with the new Token needed.
> fix: reverting back to yarn npm publish for now

- package.json
- yarn.lock
Attempting to copy the `@department-of-veteran-affairs/component-library` to the peerDependencies list to see if we can get past some testing errors inside of `vets-website`.
[department-of-veterans-affairs/va-forms-system-core#258](https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/va-forms-system-core/258)
> fix: adding component-library to peerDependencies

- package.json
- yarn.lock
Reverting the peerDependency change because it had no positive effect on the broken vets-website tests.
Also bumping package.json version so that new changes are available to use for Adam's PR.
> fix: reverting peerDependencies and bumping package

- .github/workflows/npm-publish.yml
Changing the NPM_TOKEN name to match what semantic-release needs.
> fix: changing name to NPM_TOKEN again

- .github/workflows/npm-publish.yml
In this PR I have added the bot to the list of authorized users to try and bypass the commit issue.
By adding the bot to bypass the branch protection rules SHOULD allow the bot to commit the version upgrade to package.json and complete the publish command.
[department-of-veterans-affairs/va-forms-system-core#432](https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/va-forms-system-core/432)
> fix: adding permissions for bot to push to main

- .github/workflows/npm-publish.yml
- package.json
Bumping the version to match the github version.
> fix: bumping npm version to match Github version

- package.json
- yarn.lock
Removing an unused resolution from the package.json file around npm/chalk, and attempting to kick of the `feat:` Github release information from last PR.
> feat: remove unused resolution for npm/chalk

- package-lock.json
- package.json
- src/routing/Page.tsx
This PR forces validation on clicking the `Back To Review Page` button in preparation for the fix described in the ticket below.
[department-of-veterans-affairs/va-forms-system-core#479](https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/va-forms-system-core/479)
> fix(479): validate form errors on back to review button

- package-lock.json
- package.json
- yarn.lock
Upgrading semantic-release to 19.0.3 in package.json.
[department-of-veterans-affairs/va-forms-system-core#489](https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/va-forms-system-core/489)
> fix(489): upgrade semantic-release to 19.0.3

- package.json
- src/form-data/ReviewPage.tsx
- src/routing/Page.tsx
Ensures that no duplicate IDs are found on the review page. Ensures that the Edit link on the review page has an adequate aria-label attribute, so that screen reader users know what they are about to edit. Also ensure that focus is set on the appropriate Edit link when the user activates the Back To Review Page button, so they put back to the place that initiated the edit view.
https://github.com/department-of-veterans-affairs/va-forms-system-core/issues/547
Yes
https://user-images.githubusercontent.com/5934582/185257142-3f64f6e0-f5b1-4955-88ed-7cd28d39c495.mov
> fix(#547): Ensure that no duplicate IDs are found on the review page

- package.json
When the fields are not in schema formik doesn't register the field in initial values. Sometimes, there are data points (previously used in UI schema) that need to be used for the sole purpose of showing and hiding different fields. When these fields are not registered, formik doesn't hook into any validation functions for it. This needs to be added so formik registers it as an initial value.
Bumping version to 1.5.0 for this new feature.
[department-of-veterans-affairs/va-forms-system-core#570](https://github.com/department-of-veterans-affairs/va-forms-system-core/issues/570)
> feat(#570): adding uiFormikValues to initialValues object

- package.json
- src/form-builder/CheckboxFieldGroup.tsx
This fix prevents a bug with the burial demo form where the user is unable to proceed to the next step due to the checkbox group's value being set to `false`, even if its value has been set.
https://github.com/department-of-veterans-affairs/va-forms-system-core/issues/593
https://user-images.githubusercontent.com/5934582/188240599-96732709-3b97-4878-82cd-d977c8cadc52.mov
> Set value of the checkbox group to `false` if there isn’t a value defined
